### ISSUE TITLE
Fetch Doxed Noun Images

### ISSUE THREAD

**Issue by cha0sg0d** [personaelabs/nym#108]
A sub issue for #81 and #104 

Goal:
- Have a performant way to load a doxed wallet's actual noun images (whether a multi-sig or an EOA) into the frontend.

Step 1:
- [ ] Figure out a spec / protocol (ie, is fetching directly from on-chain feasible performance wise?)

Step 2:
- [ ] Implement Step 1.

**Comment by lsankar4033** [comment]
on it

**Comment by lsankar4033** [comment]
quick update:

two calls to the noun token contract required on-chain for each profile pic generation:
1. `tokenOfOwnerByIndex(ADDRESS, 0)` -> tokenID
2. `seeds(tokenID`)

can then use `buildSVG(seeds)` as @amirgamil used in his PR for random pics. 

I'm going to see how painful it is to pull N = 20 profile pics using these two calls from my machine. 

Want to avoid caching as we'd need to update the cache on NFT xfers...

**Comment by cha0sg0d** [comment]
could we also grab the images and cache them as part of the merkle cron job?

Sent from Proton Mail for iOS

El mar, 16 may., 2023 a las 7:37 p.m., Lakshman Sankar ***@***.***(mailto:El mar, 16 may., 2023 a las 7:37 p.m., Lakshman Sankar <<a href=)> ha escrito:

**Comment by DanTehrani** [comment]
> quick update:
> 
> two calls to the noun token contract required on-chain for each profile pic generation:
> 
> 1. `tokenOfOwnerByIndex(ADDRESS, 0)` -> tokenID
> 2. `seeds(tokenID`)
> 
> can then use `buildSVG(seeds)` as @amirgamil used in his PR for random pics.
> 
> I'm going to see how painful it is to pull N = 20 profile pics using these two calls from my machine.
> 
> Want to avoid caching as we'd need to update the cache on NFT xfers...

@lsankar4033  cc @cha0sg0d  @amirgamil 
Do you think fetching the seeds from the Nouns Subgraph will be easier? Since we already have a cron job that will run every 5min, we can fetch the seeds along the list of nouns, generate the SVGs, and store the SVGs in the database as text.

And are we planning to use ENS avatars for delegates? or do you think we can use the noun image for the delegates as well, with something to indicate that the user is a delegate?  (like the purple circle around the image for nym)

**Comment by lsankar4033** [comment]
fetching the seeds from the subgraph makes sense, but we'd still need to find the tokenID held by each address (1 query to chain).

But yes, no reason not to cache tokenID -> seed as this is unchanging (vs. address -> first tokenID, which may change if someone sells/trades)

**Comment by DanTehrani** [comment]
@lsankar4033 
I might be missing something, but to just share info I'm seeing, it seems like we can fetch the mapping (tokenId -> address -> seed) from the subgraph. 

<img width="1292" alt="Screenshot 2023-05-17 at 17 35 29" 
src="https://github.com/personaelabs/nym/assets/36762093/3b15a3de-d7fa-4555-a8c1-4cbb287f82f3">


(My confusion might be coming from not understanding where ENS plays a role)

**Comment by lsankar4033** [comment]
simple alternative may be to just use the ENS avatar specified on the ENS record itself (ie. as returned by https://wagmi.sh/react/hooks/useEnsAvatar)

will weigh the options and make a decision

**Comment by cha0sg0d** [comment]
> simple alternative may be to just use the ENS avatar specified on the ENS record itself (ie. as returned by https://wagmi.sh/react/hooks/useEnsAvatar)
> 
> will weigh the options and make a decision

to clarify, this would mean not showing the user's associated noun, just their ens image (if set)? Also, we'd still probably want to cache this data somewhere, but I'm unsure if wagmi does that for us.

**Comment by lsankar4033** [comment]
yes that's right. I'm leaning towards caching no matter what

**Comment by lsankar4033** [comment]
most recent decision is to use `getENSAvatar` for this and not cache (cc @cha0sg0d )
