### ISSUE TITLE
Will Price UI Feedback

### ISSUE THREAD

**Issue by grace-fagan** [personaelabs/nym#124]
- [ ] Option to create a new nym or select an existing nym should be the default action instead of selecting your doxed name
- [ ] Very explicit feedback to the user when submitting a new post
> Solutions:
> - Scroll to the new post
> - More detailed button response -- submitting content, creating proof, etc. instead of a generic spinner
> - Checkmark on successful submission (in addition to scrolling to new post)

**Comment by grace-fagan** [comment]
@lsankar4033 Feel free to add to this list!

**Comment by lsankar4033** [comment]
- [ ] deep link to comment/posts, so easy to share in other venues
- [ ] aggregate statistics on user page, num upvotes || num threads participated in

**Comment by cha0sg0d** [comment]
Updating this. Everything above is done except for:

TODO:
- [ ] Have a share button that has a deep link + update routing when a user clicks on a post from `user` or `posts` page.

**Comment by cha0sg0d** [comment]
All done by #154
