### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by lsankar4033** [personaelabs/nym#29]
https://www.figma.com/file/upkN9a1dsGukoA4ataKWad/Prop-150-%E2%80%94-Hey-Anoun?node-id=612%3A12660&t=zjD2WOgDeNqLd3nR-1

- View past comments/discussions for a given nym/ENS name
- Total upvotes karma score

**Comment by cha0sg0d** [comment]
TODO: 

- [ ] Make a design for this in Figma

**Comment by cha0sg0d** [comment]
Closed by #81
