### ISSUE TITLE
Spec out Notifications

### ISSUE THREAD

**Issue by cha0sg0d** [personaelabs/nym#73]
- Web Push
- In-App

**Comment by cha0sg0d** [comment]
Potential subscription options:
- You subscribe to a specific user's activity
- You subscribe to a specific post
- You get a daily summary of notifications

In-app options
- You get a list of responses / upvotes to your posts / nyms in the last 24 hours

**Comment by DanTehrani** [comment]
https://nym-git-dev-personaelabs.vercel.app/posts/0xfbf666c7e57df6025ef32752f70f28d8d1085fef375ba10c8c06c44065fe661f

**Comment by cha0sg0d** [comment]
> https://nym-git-dev-personaelabs.vercel.app/posts/0xfbf666c7e57df6025ef32752f70f28d8d1085fef375ba10c8c06c44065fe661f

This seems like a great place to start! @DanTehrani  If you want to take this on, perhaps you could start just by thinking about our data model? We have a list of nyms + addresses in localstorage, we'd have to do a client-side query of all of the posts to find updates, we'd need to know the time of the user's last activity in the app, etc...

**Comment by cha0sg0d** [comment]
Closed by #162
