### ISSUE TITLE
ENS + Avatar + Color

### ISSUE THREAD

**Issue by cha0sg0d** [personaelabs/nym#81]
Fetching a user's profile picture is a non-trivial task. 

In the case of a nym, we can use our gravatar #63 .

In the case of a doxxed address, do we want to use a default image? or fetch an image potentially associated with their ENS.

Ideally we avoid a case where our page loads, but we're still waiting on images to appear.

This task entails:
- [x] Gravatars for nyms and as a default for doxxed addresses
- [ ] Getting a user's ENS name instead of their address.
- [x] thinking about if it's worth it to fetch doxed ENS images
- [x] implementing the gravatar flow in a performant way in the frontend.
- [ ] Add a `Nym` design element to the Nouns svgs (just a circle for now).
- [ ] Add ENS Avatar to doxed user addresses 
 

#90 Closed the basics, now we need to think about ENS avatars + addresses.

**Comment by lsankar4033** [comment]
as mentioned on call today, strong belief that for doxed users (all of whom we know are nouners), the simplest approach is to deterministically pick the 'first' noun in some way (i.e. lowest noun ID)

the noun art itself should be completely retrievable from the chain (i.e. https://github.com/nounsDAO/nouns-monorepo/blob/10bb478328bdb5f4c5efffed9a8c5186f9fe974a/packages/nouns-contracts/contracts/libs/NFTDescriptorV2.sol#L60), although may make sense to cache. will see what other sites in teh nouniverse are doing

**Comment by lsankar4033** [comment]
I think it could be worth to fetch doxed noun images; feel free to assign issue to me if you think makes sense @cha0sg0d

**Comment by cha0sg0d** [comment]
> I think it could be worth to fetch doxed noun images; feel free to assign issue to me if you think makes sense @cha0sg0d

@lsankar4033 as you wish! #108 is a live issue
